[package]
name = "edit-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
const_format = "0.2.33"
libc = "0.2.162"
regex = "1.11.1"
terminal-utils = { version = "0.1.0", default-features = false }
thiserror = "2.0.1"
